//! Conformance suite for the tracked-push extension: weir-core's decoder vs.
//! `docs/conformance/wire_v1_tracked_vectors.json`.
//!
//! Separate from `conformance.rs` for the same reason the JSON is separate from
//! `wire_v1_vectors.json`: that file is frozen and is read by five polyglot demo
//! clients whose decoders know message types `0x01..=0x05`. A `PushTracked`
//! (`0x06`) vector in there would make every one of them fail on a frame they
//! are *correct* to reject.
//!
//! The vectors were generated by `gen_tracked_vectors.py`, whose CRC-32 and
//! SHA-256 come from Python's `zlib` and `hashlib` — implementations independent
//! of `crc32fast` and `sha2`. So a vector can only pass here if both stacks
//! agree on every byte of the frame *and* of the record-id digest.

use serde_json::Value;
use weir_core::{
    COORDINATE_FIXED_LEN, COORDINATE_VERSION, CoordinateError, Durability, Envelope,
    MAX_SEGMENT_NAME_LEN, MAX_TRACKED_ACK_PAYLOAD_LEN, MessageType, RecordCoordinate, WIRE_VERSION,
};

const VECTORS_JSON: &str = include_str!("../../../docs/conformance/wire_v1_tracked_vectors.json");

fn from_hex(s: &str) -> Vec<u8> {
    assert!(
        s.len().is_multiple_of(2),
        "hex string must have even length: {s:?}"
    );
    fn nibble(c: u8) -> u8 {
        match c {
            b'0'..=b'9' => c - b'0',
            b'a'..=b'f' => c - b'a' + 10,
            _ => panic!("invalid hex digit: {:?}", c as char),
        }
    }
    s.as_bytes()
        .chunks(2)
        .map(|pair| (nibble(pair[0]) << 4) | nibble(pair[1]))
        .collect()
}

fn to_hex(bytes: &[u8]) -> String {
    let mut s = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        s.push_str(&format!("{b:02x}"));
    }
    s
}

/// Maps a `CoordinateError` to the stable tag the vectors name. This is the
/// contract surface: every coordinate rejection vector names one of these.
fn coordinate_error_tag(e: &CoordinateError) -> &'static str {
    match e {
        CoordinateError::Truncated { .. } => "Truncated",
        CoordinateError::UnsupportedVersion { .. } => "UnsupportedVersion",
        CoordinateError::SegmentTooLong { .. } => "SegmentTooLong",
        CoordinateError::LengthMismatch { .. } => "LengthMismatch",
        CoordinateError::SegmentNotUtf8 => "SegmentNotUtf8",
        // CoordinateError is #[non_exhaustive]: a new variant must be given a
        // tag here before a vector can reference it, rather than being silently
        // mis-tagged as an existing one.
        other => panic!("conformance: unmapped CoordinateError variant {other:?}"),
    }
}

fn message_type_name(mt: MessageType) -> &'static str {
    match mt {
        MessageType::Push => "Push",
        MessageType::Ack => "Ack",
        MessageType::Nack => "Nack",
        MessageType::HealthCheck => "HealthCheck",
        MessageType::HealthCheckResponse => "HealthCheckResponse",
        MessageType::PushTracked => "PushTracked",
        MessageType::AckTracked => "AckTracked",
    }
}

fn durability_name(d: Durability) -> &'static str {
    match d {
        Durability::Durable => "Durable",
        Durability::Buffered => "Buffered",
    }
}

fn doc() -> Value {
    serde_json::from_str(VECTORS_JSON).expect("tracked vectors file is valid JSON")
}

#[test]
fn vectors_file_pins_the_protocol_constants() {
    // If the vectors were generated against different constants than this build
    // compiles with, every byte comparison below is meaningless.
    let doc = doc();
    assert_eq!(doc["wire_version"].as_u64().unwrap(), WIRE_VERSION as u64);
    assert_eq!(
        doc["coordinate_version"].as_u64().unwrap(),
        COORDINATE_VERSION as u64
    );
    assert_eq!(
        doc["coordinate_fixed_len"].as_u64().unwrap(),
        COORDINATE_FIXED_LEN as u64
    );
    assert_eq!(
        doc["max_segment_name_len"].as_u64().unwrap(),
        MAX_SEGMENT_NAME_LEN as u64
    );
    assert_eq!(
        doc["max_tracked_ack_payload_len"].as_u64().unwrap(),
        MAX_TRACKED_ACK_PAYLOAD_LEN as u64
    );
}

#[test]
fn every_frame_vector_decodes_and_round_trips() {
    let doc = doc();
    let vectors = doc["frame_vectors"]
        .as_array()
        .expect("frame_vectors array");
    assert!(!vectors.is_empty(), "the vectors file must not be empty");

    for v in vectors {
        let name = v["name"].as_str().unwrap();
        let buf = from_hex(v["hex"].as_str().unwrap());
        let expected = v["decode"].as_str().unwrap();
        assert_eq!(
            expected, "ok",
            "{name}: only 'ok' frame vectors are defined"
        );

        let env = Envelope::decode(&buf).unwrap_or_else(|e| panic!("{name}: decode failed: {e:?}"));
        let h = env.header();
        assert_eq!(
            message_type_name(h.message_type()),
            v["message_type"].as_str().unwrap(),
            "{name}: message_type"
        );
        assert_eq!(
            durability_name(h.durability()),
            v["durability"].as_str().unwrap(),
            "{name}: durability"
        );
        assert_eq!(
            h.flags() as u64,
            v["flags"].as_u64().unwrap(),
            "{name}: flags"
        );
        assert_eq!(
            to_hex(env.payload()),
            v["payload_hex"].as_str().unwrap(),
            "{name}: payload"
        );
        assert_eq!(
            to_hex(&env.encode()),
            v["hex"].as_str().unwrap(),
            "{name}: re-encode is not byte-identical"
        );
    }
}

/// The compatibility claim, executed rather than asserted: the frozen v1 vector
/// set contains no `0x06`/`0x07` frame, so nothing an existing client reads has
/// moved. If a tracked frame were ever added to `wire_v1_vectors.json` this
/// fails, and the five polyglot clients in CI would fail right after it.
#[test]
fn the_frozen_v1_vectors_contain_no_tracked_frame() {
    const V1: &str = include_str!("../../../docs/conformance/wire_v1_vectors.json");
    let doc: Value = serde_json::from_str(V1).unwrap();
    for v in doc["vectors"].as_array().unwrap() {
        let buf = from_hex(v["hex"].as_str().unwrap());
        // Byte 5 is message_type; short buffers (truncation vectors) have none.
        if let Some(&mt) = buf.get(5) {
            assert!(
                mt != 0x06 && mt != 0x07,
                "vector {:?} puts a tracked message type in the frozen v1 file; \
                 every v1-only decoder rejects it and CI's polyglot clients will fail",
                v["name"].as_str().unwrap()
            );
        }
    }
}

#[test]
fn every_coordinate_vector_matches_the_decoder() {
    let doc = doc();
    let vectors = doc["coordinate_vectors"]
        .as_array()
        .expect("coordinate_vectors array");
    assert!(!vectors.is_empty(), "the vectors file must not be empty");

    let mut ok_seen = 0;
    let mut reject_seen = 0;
    for v in vectors {
        let name = v["name"].as_str().unwrap();
        let buf = from_hex(v["hex"].as_str().unwrap());
        let expected = v["decode"].as_str().unwrap();

        match RecordCoordinate::decode(&buf) {
            Ok(c) => {
                assert_eq!(expected, "ok", "{name}: expected rejection, but it decoded");
                assert_eq!(
                    c.segment(),
                    v["segment"].as_str().unwrap(),
                    "{name}: segment"
                );
                assert_eq!(c.index(), v["index"].as_u64().unwrap(), "{name}: index");
                assert_eq!(
                    c.record_id_hex(),
                    v["record_id_hex"].as_str().unwrap(),
                    "{name}: record_id — the Rust sha2 digest disagrees with the \
                     Python hashlib one the vector was generated with"
                );
                assert_eq!(
                    to_hex(&c.encode()),
                    v["hex"].as_str().unwrap(),
                    "{name}: re-encode is not byte-identical"
                );
                ok_seen += 1;
            }
            Err(e) => {
                assert_eq!(
                    coordinate_error_tag(&e),
                    expected,
                    "{name}: wrong rejection reason"
                );
                reject_seen += 1;
            }
        }
    }
    assert!(
        ok_seen > 0 && reject_seen > 0,
        "the suite must cover both acceptance and rejection ({ok_seen} ok, {reject_seen} rejected)"
    );
}
