#!/usr/bin/env python3
"""Generate conformance vectors for weir-attest's chain construction.

The whole value of a hash chain is that two independent implementations agree
on every byte. A vector file generated by calling weir's own Rust code would
prove nothing — it would pass against a broken digest just as happily as
against a correct one. This generator instead computes the chain FROM THE
SPEC, using nothing but stdlib `hashlib`, and shares no code and no constants
by import with `crates/weir-attest/src/chain.rs`. A vector can therefore only
pass in weir-attest if both sides independently agree on:

  * the domain separator and its position (first, over the whole of H0's
    input, not mixed in anywhere else);
  * H0's exact field order and width — format_version as one byte, shard_id
    as a little-endian u16, created_at as a little-endian SIGNED i64, and the
    segment name length-prefixed as a little-endian u64 ahead of its bytes;
  * that H_i folds the PREVIOUS head with that record's RecordId, in that
    order, one step per record; and
  * that RecordId's index is the record's 1-based position within its
    segment, not a 0-based offset — the off-by-one that would make every
    downstream sink's replay math disagree with weir's own count by one.

Any one of those, gotten wrong on either side, changes every hash from that
point on, so there is nowhere for a mismatch to hide.

Run it and freeze the output:

    python3 docs/conformance/gen_attest_vectors.py > docs/conformance/attest_v1_vectors.json
"""
import json

import hashlib

DOMAIN_SEP = b"weir-attest-v1"


def record_id(segment: str, index: int, payload: bytes) -> bytes:
    """RecordId = SHA256(len(segment) u64 LE ++ segment ++ index u64 LE ++
    len(payload) u64 LE ++ payload). `index` is 1-based."""
    h = hashlib.sha256()
    h.update(len(segment.encode()).to_bytes(8, "little"))
    h.update(segment.encode())
    h.update(index.to_bytes(8, "little"))
    h.update(len(payload).to_bytes(8, "little"))
    h.update(payload)
    return h.digest()


def chain_origin(
    prev_head: bytes, format_version: int, shard_id: int, created_at: int, segment_name: str
) -> bytes:
    """H0 = SHA256(DOMAIN_SEP ++ prev_head ++ format_version(1) ++
    shard_id u16 LE ++ created_at i64 LE ++ len(segment_name) u64 LE ++
    segment_name)."""
    h = hashlib.sha256()
    h.update(DOMAIN_SEP)
    h.update(prev_head)
    h.update(bytes([format_version]))
    h.update(shard_id.to_bytes(2, "little"))
    h.update(created_at.to_bytes(8, "little", signed=True))
    name = segment_name.encode()
    h.update(len(name).to_bytes(8, "little"))
    h.update(name)
    return h.digest()


def chain_step(prev_head: bytes, rid: bytes) -> bytes:
    """Hi = SHA256(H(i-1) ++ RecordId_i)."""
    return hashlib.sha256(prev_head + rid).digest()


ORIGIN_HEX = bytes(32).hex()


def build_vector(name, notes, prev_head_hex, format_version, shard_id, created_at,
                  segment_name, records):
    """Computes one full chain and returns the vector dict the Rust runner checks.

    `records` is a list of raw payload bytes, in the order they sit in the
    segment; RecordId's index is derived from position (1-based), not carried
    separately, so the caller cannot accidentally desync the two.
    """
    prev_head = bytes.fromhex(prev_head_hex)
    h0 = chain_origin(prev_head, format_version, shard_id, created_at, segment_name)

    record_ids = []
    h_i = []
    head = h0
    for i, payload in enumerate(records, start=1):
        rid = record_id(segment_name, i, payload)
        record_ids.append(rid)
        head = chain_step(head, rid)
        h_i.append(head)

    return {
        "name": name,
        "notes": notes,
        "prev_head": prev_head_hex,
        "format_version": format_version,
        "shard_id": shard_id,
        "created_at": created_at,
        "segment_name": segment_name,
        "records_hex": [r.hex() for r in records],
        "record_ids_hex": [r.hex() for r in record_ids],
        "h0": h0.hex(),
        "h_i": [h.hex() for h in h_i],
        "head": h_i[-1].hex(),
    }


vectors = []

vectors.append(build_vector(
    "single_record_chain",
    "The smallest possible chain: one record. Pins H0 and a single chain_step "
    "together — get either the domain separator, the header field order, or "
    "the fold wrong and this already fails, before any multi-record vector "
    "below gets a chance to.",
    ORIGIN_HEX, 1, 0, 0,
    "shard_00/seg_00000001.wab.sealed", [b"solo"],
))

vectors.append(build_vector(
    "three_record_chain",
    "Three records folded in sequence. Pins that h_1, h_2 and the final head "
    "(h_3) are each SHA256(previous head ++ that record's RecordId) computed "
    "in order — not three independent digests, and not folded out of order.",
    ORIGIN_HEX, 1, 7, 1_700_000_000_000_000_000,
    "shard_07/seg_00000001.wab.sealed", [b"alpha", b"beta", b"gamma"],
))

vectors.append(build_vector(
    "three_record_chain_different_segment_name",
    "Identical prev_head, header and three records as 'three_record_chain' — "
    "only segment_name changes (…seg_00000001 -> …seg_00000002). Both H0 "
    "(which folds the name directly) and every RecordId (which folds the "
    "segment a record was read from) depend on it, so the head MUST differ. "
    "Catches an implementation that forgets to fold the segment name into H0, "
    "or that computes RecordId without it.",
    ORIGIN_HEX, 1, 7, 1_700_000_000_000_000_000,
    "shard_07/seg_00000002.wab.sealed", [b"alpha", b"beta", b"gamma"],
))

vectors.append(build_vector(
    "three_record_chain_reordered",
    "Identical prev_head, header, segment_name and three records as "
    "'three_record_chain' — only the ORDER changes (a rotation: gamma, alpha, "
    "beta). RecordId's index is a record's 1-based POSITION within the "
    "segment, so reordering reassigns every index as well as the fold order; "
    "the resulting head must differ both from 'three_record_chain' and from "
    "what an implementation would get if it reordered the fold but forgot to "
    "recompute each record's index for its new position.",
    ORIGIN_HEX, 1, 7, 1_700_000_000_000_000_000,
    "shard_07/seg_00000001.wab.sealed", [b"gamma", b"alpha", b"beta"],
))

vectors.append(build_vector(
    "nonzero_prev_head",
    "prev_head is a non-zero, non-repeating 32-byte pattern (bytes 0x00..0x1f) "
    "rather than ChainHead::ORIGIN, so an implementation that silently "
    "hardcodes the origin as H0's predecessor fails here even though every "
    "vector above it (all origin-rooted) would still pass. shard_id is "
    "0x1234, whose little-endian encoding (34 12) is not a palindrome, and "
    "created_at is -1 (all-ones once sign-extended to 8 bytes) — both chosen "
    "so a byte-order mistake or an unsigned-i64 mistake changes the digest "
    "rather than coincidentally matching.",
    bytes(range(32)).hex(), 1, 0x1234, -1,
    "shard_ab/seg_00000009.wab.sealed", [b"delta", b"epsilon"],
))

doc = {
    "domain_sep_hex": DOMAIN_SEP.hex(),
    "description": (
        "Conformance vectors for weir-attest's chain construction: H0 = "
        "SHA256(domain_sep ++ prev_head ++ format_version ++ shard_id LE u16 ++ "
        "created_at LE i64 ++ len(segment_name) LE u64 ++ segment_name), "
        "RecordId = SHA256(len(segment) LE u64 ++ segment ++ index LE u64 ++ "
        "len(payload) LE u64 ++ payload) with a 1-based index, and "
        "Hi = SHA256(H(i-1) ++ RecordId_i). Generated independently of "
        "crates/weir-attest — this file computes every hash from the spec "
        "using stdlib hashlib, sharing no code and no constants by import "
        "with the Rust implementation it checks."
    ),
    "vectors": vectors,
}

print(json.dumps(doc, indent=2))
