"""weir_wire — a pure-Python weir wire-protocol producer (v1)."""

from .client import (
    ConnectionClosed,
    NackError,
    PushResult,
    WeirClient,
    WeirError,
)
from .codec import (
    MAX_ACK_BATCH_PAYLOAD,
    MAX_BATCH_RECORDS_HARD_CAP,
    MAX_PAYLOAD_HARD_CAP,
    WIRE_VERSION,
    BatchError,
    DecodeError,
    Durability,
    Frame,
    MessageType,
    NackReason,
    decode_ack_batch,
    decode_batch_body,
    decode_frame,
    encode_ack_batch,
    encode_batch_body,
    encode_frame,
    max_response_payload,
)

__all__ = [
    "WeirClient",
    "WeirError",
    "NackError",
    "ConnectionClosed",
    "PushResult",
    "encode_frame",
    "decode_frame",
    "DecodeError",
    "Frame",
    "MessageType",
    "Durability",
    "NackReason",
    "WIRE_VERSION",
    "MAX_PAYLOAD_HARD_CAP",
    "encode_batch_body",
    "decode_batch_body",
    "encode_ack_batch",
    "decode_ack_batch",
    "BatchError",
    "MAX_BATCH_RECORDS_HARD_CAP",
    "MAX_ACK_BATCH_PAYLOAD",
    "max_response_payload",
]
