#!/usr/bin/env bash
# Launch a chaos soak in a privileged container on macOS, bounded by WALL CLOCK.
#
# WHY THIS EXISTS. A soak is bounded by time, not episode count, and the useful
# bound is often "stop by the time I wake up" rather than "run for N hours".
# This takes either a duration (4h) or a target clock time (@07:30) and turns it
# into the schedule's `max_duration_secs`.
#
# WHY IT GENERATES A SCHEDULE FILE rather than passing an override. The run
# directory records the schedule verbatim, so a schedule saying one thing while
# the run did another is a provenance defect — the same class of bug as a report
# naming a commit the run did not execute. The generated file IS what ran.
#
# Usage:
#   ./run-docker-soak.sh <base-schedule> <label> <4h | @07:30>
#
# Examples:
#   ./run-docker-soak.sh schedules/soak8h-zstd.toml office   4h
#   ./run-docker-soak.sh schedules/soak8h-zstd.toml overnight @07:30
#
# Afterwards, get the results out (the container is NOT --rm for this reason):
#   docker cp weir-soak-<label>:/src/chaos/runs ./runs-<label>
set -euo pipefail

BASE="${1:?usage: run-docker-soak.sh <base-schedule> <label> <4h|@07:30>}"
LABEL="${2:?missing label}"
SPEC="${3:?missing duration (4h) or end time (@07:30)}"

cd "$(dirname "$0")"
[ -f "$BASE" ] || { echo "no such schedule: $BASE" >&2; exit 1; }

NOW=$(date '+%s')

# ── Resolve the bound ─────────────────────────────────────────────────────────
if [[ "$SPEC" == @* ]]; then
  HHMM="${SPEC#@}"
  TARGET=$(date -j -f '%Y-%m-%d %H:%M:%S' "$(date '+%Y-%m-%d') ${HHMM}:00" '+%s' 2>/dev/null) \
    || { echo "cannot parse time '${HHMM}' (want HH:MM)" >&2; exit 1; }
  # A target already past today means tomorrow — which is the normal case for an
  # overnight run started in the evening.
  if [ "$TARGET" -le "$NOW" ]; then TARGET=$((TARGET + 86400)); fi
  SECS=$((TARGET - NOW))
  ENDS_AT=$(date -r "$TARGET" '+%a %H:%M')
else
  case "$SPEC" in
    *h) SECS=$(( ${SPEC%h} * 3600 )) ;;
    *m) SECS=$(( ${SPEC%m} * 60 )) ;;
    *)  SECS="$SPEC" ;;
  esac
  ENDS_AT=$(date -r $((NOW + SECS)) '+%a %H:%M')
fi

[ "$SECS" -ge 300 ] || { echo "refusing: computed duration ${SECS}s is under 5 minutes" >&2; exit 1; }

# ── Generate the schedule that will actually run ──────────────────────────────
# The seed must differ per run: run_id derives from it, so reusing one collides
# with the earlier run's directory and makes two runs indistinguishable.
SEED=$(printf '0x%X' $(( (NOW & 0xFFFFF) | 0x100000 )))
mkdir -p schedules/generated
GEN="schedules/generated/${LABEL}.toml"

{
  echo "# GENERATED by run-docker-soak.sh at $(date '+%Y-%m-%d %H:%M:%S %Z')."
  echo "# Base: ${BASE}   Bound: ${SPEC}   Ends ~${ENDS_AT}"
  echo "# Edit the BASE, not this file — this is regenerated on every launch."
  echo
  sed -e "s/^seed = .*/seed = ${SEED}/" \
      -e "s/^max_duration_secs = .*/max_duration_secs = ${SECS}/" "$BASE"
} > "$GEN"

grep -qE '^max_duration_secs = '"${SECS}"'$' "$GEN" || {
  echo "refusing: base schedule has no max_duration_secs line to substitute" >&2
  exit 1; }

NAME="weir-soak-${LABEL}"
docker rm -f "$NAME" >/dev/null 2>&1 || true

# ── Keep the Mac awake ────────────────────────────────────────────────────────
# Idle/display/disk sleep only. A CLOSED LID ON BATTERY still sleeps, and takes
# Docker's VM down with it — leave the lid open and stay on mains.
nohup caffeinate -dimsu -t $((SECS + 900)) >/dev/null 2>&1 &
CAF=$!

docker run -d --privileged --name "$NAME" \
  -v "$PWD/orchestrator:/src/chaos/orchestrator:ro" \
  -v "$PWD/schedules:/src/chaos/schedules:ro" \
  weir-chaos-gate \
  python3 -u orchestrator/run.py "$GEN" >/dev/null

cat <<EOF
launched  ${NAME}
schedule  ${GEN}  (seed ${SEED})
bound     ${SECS}s — ends ~${ENDS_AT}
caffeinate pid ${CAF}, expires $(date -r $((NOW + SECS + 900)) '+%H:%M')

watch     docker logs -f ${NAME}
progress  docker logs ${NAME} 2>&1 | grep -c '^episode'
collect   docker cp ${NAME}:/src/chaos/runs ./runs-${LABEL}

Leave the lid OPEN and stay on mains. Tailscale must stay down — its utun
interfaces break Docker Desktop's VM networking on this machine.
EOF
