//! Frozen conformance suite: weir-attest's chain construction vs.
//! `docs/conformance/attest_v1_vectors.json`.
//!
//! The vectors come from `gen_attest_vectors.py`, which computes every hash
//! from the spec using Python's stdlib `hashlib` — no code and no constants
//! shared by import with this crate. A vector can therefore only pass here if
//! two independent SHA-256 implementations agree on every byte of H0, of
//! every `RecordId`, and of every `H_i` in between. A vector file generated by
//! calling `chain_origin`/`chain_step` themselves would prove nothing: it
//! would pass against a broken digest exactly as happily as a correct one.

use weir_attest::chain::{chain_origin, chain_step};
use weir_attest::{ChainHead, DOMAIN_SEP};
use weir_sink_sdk::{Payload, RecordId};
use weir_wab::format::{
    SEGMENT_HEADER_LEN, SEGMENT_MAGIC, SegmentHeaderMeta, parse_segment_header,
};

const VECTORS_JSON: &str = include_str!("../../../docs/conformance/attest_v1_vectors.json");

fn from_hex(s: &str) -> Vec<u8> {
    assert!(
        s.len().is_multiple_of(2),
        "hex string must have even length: {s:?}"
    );
    fn nibble(c: u8) -> u8 {
        match c {
            b'0'..=b'9' => c - b'0',
            b'a'..=b'f' => c - b'a' + 10,
            _ => panic!("invalid hex digit: {:?}", c as char),
        }
    }
    s.as_bytes()
        .chunks(2)
        .map(|pair| (nibble(pair[0]) << 4) | nibble(pair[1]))
        .collect()
}

/// Builds a [`SegmentHeaderMeta`] from raw field values. `SegmentHeaderMeta` is
/// `#[non_exhaustive]`, so outside weir-wab it cannot be built with a struct
/// literal even with every field named — round-trip it through weir-wab's own
/// byte-level constants and `parse_segment_header` instead, exactly as
/// `crates/weir-attest/src/chain.rs`'s own unit tests do.
fn header(format_version: u8, shard_id: u16, created_at: i64) -> SegmentHeaderMeta {
    let mut buf = [0u8; SEGMENT_HEADER_LEN];
    buf[0..4].copy_from_slice(&SEGMENT_MAGIC);
    buf[4] = format_version;
    buf[5] = 0; // flags — Compression::None under v1, which is all these vectors use.
    buf[6..8].copy_from_slice(&shard_id.to_le_bytes());
    buf[8..16].copy_from_slice(&created_at.to_le_bytes());
    parse_segment_header(&buf).expect("hand-built header is valid")
}

fn doc() -> serde_json::Value {
    serde_json::from_str(VECTORS_JSON).expect("attest vectors file is valid JSON")
}

#[test]
fn vectors_file_pins_the_domain_separator() {
    // If the vectors were generated against a different domain separator than
    // this build compiles with, every hash comparison below is meaningless.
    let doc = doc();
    assert_eq!(
        doc["domain_sep_hex"].as_str().unwrap(),
        hex_of(DOMAIN_SEP),
        "the vectors' domain separator must match weir_attest::DOMAIN_SEP"
    );
}

fn hex_of(bytes: &[u8]) -> String {
    let mut s = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        s.push_str(&format!("{b:02x}"));
    }
    s
}

#[test]
fn every_vector_reproduces_h0_every_h_i_and_the_final_head() {
    let doc = doc();
    let vectors = doc["vectors"].as_array().expect("vectors array");
    // A silently-empty file would report zero failures and "pass" — this
    // guards against that, matching the guard in weir-core's own conformance
    // suites (see tests/conformance_batch.rs).
    assert!(!vectors.is_empty(), "the vectors file must not be empty");

    for v in vectors {
        let name = v["name"].as_str().expect("name");

        let prev_head = ChainHead::from_hex(v["prev_head"].as_str().unwrap())
            .unwrap_or_else(|e| panic!("{name}: bad prev_head hex: {e}"));
        let format_version = v["format_version"].as_u64().unwrap() as u8;
        let shard_id = v["shard_id"].as_u64().unwrap() as u16;
        let created_at = v["created_at"].as_i64().unwrap();
        let segment_name = v["segment_name"].as_str().unwrap();
        let meta = header(format_version, shard_id, created_at);

        let records_hex = v["records_hex"].as_array().unwrap();
        let record_ids_hex = v["record_ids_hex"].as_array().unwrap();
        let h_i = v["h_i"].as_array().unwrap();
        assert_eq!(
            records_hex.len(),
            record_ids_hex.len(),
            "{name}: records_hex and record_ids_hex must be the same length"
        );
        assert_eq!(
            records_hex.len(),
            h_i.len(),
            "{name}: records_hex and h_i must be the same length"
        );
        assert!(
            !records_hex.is_empty(),
            "{name}: every vector must carry at least one record"
        );

        let mut head = chain_origin(prev_head, &meta, segment_name);
        assert_eq!(
            head.to_hex(),
            v["h0"].as_str().unwrap(),
            "{name}: H0 mismatch"
        );

        for (i, record_hex) in records_hex.iter().enumerate() {
            let payload = Payload::copy_from_slice(&from_hex(record_hex.as_str().unwrap()));
            // 1-based, matching RecordId's contract and chain_segment/verify_segment's
            // own indexing — this is the off-by-one the reordered vector exists to catch.
            let index = (i as u64) + 1;
            let rid = RecordId::for_record(segment_name, index, &payload);
            assert_eq!(
                hex_of(rid.as_bytes()),
                record_ids_hex[i].as_str().unwrap(),
                "{name}: RecordId mismatch at index {index}"
            );

            head = chain_step(head, &rid);
            assert_eq!(
                head.to_hex(),
                h_i[i].as_str().unwrap(),
                "{name}: H_{index} mismatch"
            );
        }

        assert_eq!(
            head.to_hex(),
            v["head"].as_str().unwrap(),
            "{name}: final head mismatch"
        );
    }
}
